name: tox

on:
  pull_request:
  push:
    branches: [master]

jobs:
  tox:
    strategy:
      matrix:
        python_version: [3.7, 3.8]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python_version: ${{ matrix.python_version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: run-tox
        run: tox
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        if: matrix.python_version == '3.8' && matrix.os  == 'ubuntu-latest'
        with:
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: true
